/*
 * MIT License
 *
 * Copyright (c) 2020, 2025 Mark Schmieder
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * This file is part of the fxpdfreport Library
 *
 * You should have received a copy of the MIT License along with the fxpdfreport
 * Library. If not, see <https://opensource.org/licenses/MIT>.
 *
 * Project: https://github.com/mhschmieder/fxpdfreport
 */
package com.mhschmieder.fxpdfreport.util;

import com.mhschmieder.jcommons.io.FileStatus;
import com.qoppa.pdfWriter.PDFDocument;
import javafx.print.Paper;
import org.apache.commons.math3.util.FastMath;

import java.awt.print.PageFormat;
import java.io.OutputStream;

/**
 * Static utility class to wrap the conversion and export of HTML content to PDF
 * graphics in report format using Qoppa jPdfWriter with no layout assumptions.
 */
public final class PdfWriterTools {

    /**
     * Include this attribution in your About Box and Splash Screen if you make
     * use of the PDF Export facility in this class, as this is a contractual
     * requirement for using the free jPDFWriter package from Qoppa.
     */
    public static final String JPDFWRITER_ATTRIBUTION
            = "PDF Technology by Qoppa Software, LLC – www.qoppa.com";

    // NOTE: The constructor is disabled, as this is a static class.
    private PdfWriterTools() {}

    public static FileStatus saveHtmlToPdf( final OutputStream outputStream,
                                            final String htmlBuffer ) {
        // Avoid throwing unnecessary exceptions by filtering for bad streams.
        if ( outputStream == null ) {
            return FileStatus.WRITE_ERROR;
        }

        try {
            // Create a Page Format of standard Letter size with no margins.
            // NOTE: For now, we take the minimum for Letter and A4 in each
            //  dimension, so that the output will print properly for either one.
            // TODO: Use A4 size instead, if Locale isn't US or Canada?
            // TODO: Pass this in as a parameter instead, and present in GUI?
            final double pageWidth = FastMath.min( Paper.NA_LETTER.getWidth(),
                                                   Paper.A4.getWidth() );
            final double pageHeight = FastMath.min( Paper.NA_LETTER.getHeight(),
                                                    Paper.A4.getHeight() );
            final java.awt.print.Paper paper = new java.awt.print.Paper();
            paper.setSize( pageWidth, pageHeight );
            paper.setImageableArea( 0.0d, 0.0d, pageWidth, pageHeight );
            final PageFormat pageFormat = new PageFormat();
            pageFormat.setPaper( paper );

            // Convert the HTML to PDF using jPDFWriter and then write to disc.
            // This may be from the original file, if the user opened a legacy
            // Project Report or a legacy Converted Project, or it may be from a
            // newly converted Project generated by the XML to HTML transformer.
            // TODO: Set Document Info fields (metadata) for PDF/A standard.
            final byte[] htmlByteArray = htmlBuffer.getBytes();
            final PDFDocument document = PDFDocument
                    .loadHTML( htmlByteArray, null, pageFormat, true );

            // Save the PDF Document, using an OutputStream vs. a Writer due to
            // the entire file contents being stored as a byte array.
            document.saveDocument( outputStream );

            // Return the PDF document's status, which subsumes exceptions.
            return FileStatus.SAVED;
        }
        catch ( final Exception e ) {
            e.printStackTrace();
            return FileStatus.WRITE_ERROR;
        }
    }
}
